name="stratum"
compatibility_date = "2023-02-05"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "stratum"
database_id = "d82795eb-def6-48d6-bfd1-e44f2505e943"